"""Target-specific engineered and frozen-encoder representations."""

from .cache_provenance import (
    FrozenCacheVerification,
    confirmatory_cache_provenance_record,
    ordered_sample_ids_sha256,
    primary_cache_provenance_record,
    verify_frozen_cache_sidecar,
)
from .engineered import (
    EngineeredFeatureSet,
    build_engineered_feature_set,
    engineered_feature_names,
    extract_engineered_features,
    save_engineered_feature_cache,
    select_target_morphometrics,
)
from .imagenet import (
    EmbeddingResult,
    PretrainedWeightsUnavailableError,
    ResNet18EmbeddingConfig,
    ResNet18SmokeResult,
    extract_resnet18_embeddings,
    load_embedding_cache,
    official_resnet18_weight_cache_path,
    run_resnet18_embedding_smoke,
    save_embedding_cache,
)
from .pannuke import (
    FULL_MANIFEST_CACHE_MIN_FREE_BYTES,
    ContextMorphometricsCache,
    FullManifestCacheDiskCheck,
    InsufficientFullManifestCacheDiskSpaceError,
    PanNukeCropBatch,
    PanNukeCropConfig,
    PanNukeRepresentationArtifacts,
    build_pannuke_representation_cache,
    extract_pannuke_crop_batch,
    require_full_manifest_cache_disk_space,
    save_context_morphometrics_cache,
    save_pannuke_crop_cache,
)
from .pathology import (
    PathologyEncoderAuditRecord,
    PathologyEncoderAvailabilityAudit,
    PathologyEncoderCandidate,
    audit_pathology_encoder_availability,
    default_pathology_encoder_candidates,
    unavailable_optional_pathology_cache_provenance,
)

__all__ = [
    "FULL_MANIFEST_CACHE_MIN_FREE_BYTES",
    "ContextMorphometricsCache",
    "EmbeddingResult",
    "EngineeredFeatureSet",
    "FrozenCacheVerification",
    "FullManifestCacheDiskCheck",
    "InsufficientFullManifestCacheDiskSpaceError",
    "PanNukeCropBatch",
    "PanNukeCropConfig",
    "PanNukeRepresentationArtifacts",
    "PathologyEncoderAuditRecord",
    "PathologyEncoderAvailabilityAudit",
    "PathologyEncoderCandidate",
    "PretrainedWeightsUnavailableError",
    "ResNet18EmbeddingConfig",
    "ResNet18SmokeResult",
    "audit_pathology_encoder_availability",
    "build_engineered_feature_set",
    "build_pannuke_representation_cache",
    "confirmatory_cache_provenance_record",
    "default_pathology_encoder_candidates",
    "engineered_feature_names",
    "extract_engineered_features",
    "extract_pannuke_crop_batch",
    "extract_resnet18_embeddings",
    "load_embedding_cache",
    "official_resnet18_weight_cache_path",
    "ordered_sample_ids_sha256",
    "primary_cache_provenance_record",
    "require_full_manifest_cache_disk_space",
    "run_resnet18_embedding_smoke",
    "save_context_morphometrics_cache",
    "save_embedding_cache",
    "save_engineered_feature_cache",
    "save_pannuke_crop_cache",
    "select_target_morphometrics",
    "unavailable_optional_pathology_cache_provenance",
    "verify_frozen_cache_sidecar",
]
