"""PanNuke acquisition, validation, manifest, and duplicate-audit gate.

All operations are local and read-only with respect to the source release. This
package never downloads data, extracts archives, deletes duplicates, or changes
source annotations.
"""

from .acquisition import (
    DEFAULT_ARCHIVE_EXPECTATIONS,
    ArchiveExpectation,
    PanNukeAcquisitionError,
    build_acquisition_verification_report,
    build_pannuke_acquisition_manifest,
    git_ignore_evidence,
    validate_acquisition_manifest,
    validate_zip_member_path,
    verify_acquisition_raw_metadata_unchanged,
    write_acquisition_artifact_bundle,
    write_acquisition_manifest,
    write_json_compare_and_swap,
)
from .discovery import (
    discover_pannuke_release,
    discover_release,
    infer_fold_id,
    inspect_npy_candidate,
)
from .duplicates import (
    DuplicatePair,
    EmbeddingSignalResult,
    PatchHashRecord,
    PatchReference,
    RankedDuplicateCandidate,
    audit_duplicates,
    audit_pannuke_duplicates,
    patch_sha256,
)
from .exceptions import (
    PanNukeDiscoveryError,
    PanNukeError,
    PanNukeNotFoundError,
    PanNukeSemanticsError,
)
from .io import inventory_raw_files, locate_pannuke_root, open_npy_mmap, sha256_file
from .manifest import (
    MANIFEST_REQUIRED_COLUMNS,
    build_manifest,
    build_nucleus_manifest,
    validate_manifest_invariants,
)
from .models import (
    OFFICIAL_METRICS_CLASS_MAPPING,
    OFFICIAL_RELEASE_FOLD_IDS,
    SOURCE_PATCH_INDEPENDENCE_STATEMENT,
    ArrayInspection,
    DiscoveredFold,
    DuplicateAuditArtifacts,
    FoldValidation,
    ManifestArtifacts,
    PanNukeValidationResult,
    RawFileRecord,
    ReleaseDiscovery,
    ValidationArtifacts,
    VerifiedClassMapping,
)
from .qc_reporting import (
    MaskQCReportArtifacts,
    MaskQCReportError,
    anomaly_overlay_rgba,
    reconcile_mask_qc_result,
    validate_mask_qc_report_bundle,
    write_mask_qc_report_bundle,
)
from .validation import (
    resolve_class_mapping,
    run_validation_gate,
    validate_discovered_release,
    validate_pannuke,
    verify_raw_inventory_unchanged,
    write_overlay_grid,
)

__all__ = [
    "DEFAULT_ARCHIVE_EXPECTATIONS",
    "MANIFEST_REQUIRED_COLUMNS",
    "OFFICIAL_METRICS_CLASS_MAPPING",
    "OFFICIAL_RELEASE_FOLD_IDS",
    "SOURCE_PATCH_INDEPENDENCE_STATEMENT",
    "ArchiveExpectation",
    "ArrayInspection",
    "DiscoveredFold",
    "DuplicateAuditArtifacts",
    "DuplicatePair",
    "EmbeddingSignalResult",
    "FoldValidation",
    "ManifestArtifacts",
    "MaskQCReportArtifacts",
    "MaskQCReportError",
    "PanNukeAcquisitionError",
    "PanNukeDiscoveryError",
    "PanNukeError",
    "PanNukeNotFoundError",
    "PanNukeSemanticsError",
    "PanNukeValidationResult",
    "PatchHashRecord",
    "PatchReference",
    "RankedDuplicateCandidate",
    "RawFileRecord",
    "ReleaseDiscovery",
    "ValidationArtifacts",
    "VerifiedClassMapping",
    "anomaly_overlay_rgba",
    "audit_duplicates",
    "audit_pannuke_duplicates",
    "build_acquisition_verification_report",
    "build_manifest",
    "build_nucleus_manifest",
    "build_pannuke_acquisition_manifest",
    "discover_pannuke_release",
    "discover_release",
    "git_ignore_evidence",
    "infer_fold_id",
    "inspect_npy_candidate",
    "inventory_raw_files",
    "locate_pannuke_root",
    "open_npy_mmap",
    "patch_sha256",
    "reconcile_mask_qc_result",
    "resolve_class_mapping",
    "run_validation_gate",
    "sha256_file",
    "validate_acquisition_manifest",
    "validate_discovered_release",
    "validate_manifest_invariants",
    "validate_mask_qc_report_bundle",
    "validate_pannuke",
    "validate_zip_member_path",
    "verify_acquisition_raw_metadata_unchanged",
    "verify_raw_inventory_unchanged",
    "write_acquisition_artifact_bundle",
    "write_acquisition_manifest",
    "write_json_compare_and_swap",
    "write_mask_qc_report_bundle",
    "write_overlay_grid",
]
